User-agent: Yandex
Allow: /
Allow: /uslugi/
Allow: /nashi-raboty
Disallow: /cookie-policy
Disallow: /privacy
Disallow: /hello-world/
Disallow: /sample-page/
Disallow: /voprosy-i-otvety-faq.html
Host: https://arenda-chistoty.ru
Sitemap: https://arenda-chistoty.ru/sitemap.xml

User-agent: Googlebot
Allow: /
Allow: /uslugi/
Allow: /nashi-raboty
Disallow: /cookie-policy
Disallow: /privacy
Disallow: /hello-world/
Disallow: /sample-page/
Sitemap: https://arenda-chistoty.ru/sitemap.xml

User-agent: *
Allow: /
Disallow: /cookie-policy
Disallow: /privacy
Disallow: /hello-world/
Disallow: /sample-page/
Sitemap: https://arenda-chistoty.ru/sitemap.xml